### ISSUE TITLE
Github path to Project mapping

### ISSUE THREAD

**Issue by petericebear** [clockify/browser-extension#109]
Hi,

Is it possible to add time to a specific project based on the url (repository) where the issue belongsTo.
Like github.com/intvent/eboekhouden-php => Select default project OpenSource in Clockify?

**Comment by petericebear** [comment]
![image](https://user-images.githubusercontent.com/339796/88459787-2471a580-ce98-11ea-8f0c-d0a1d78a63a0.png)

With this input for the timer

**Comment by aleksandar-olic** [comment]
Both the input and the timer button will take repository name as project (if you have it already created in Clockify, or if you enable automatic creation in the extension's Settings). For example, if you track time on this issue, "browser-extension" will be used as the project.

You can change that, but it will affect everyone who uses the integration. You can also create a fork and use your own dev build instead of the official extension from the store.

**Comment by petericebear** [comment]
Thiss will do just fine thanks!
