### ISSUE TITLE
Not compatible with old JIRA version & onPrem ManageEngine ServiceDesk Plus

### ISSUE THREAD

**Issue by petrusali** [clockify/browser-extension#74]
Hi, tried the integration feature on my onPrem JIRA & ME SDP but it doesn't work. Please help.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/331116/79061287-da81fc80-7cb8-11ea-99ef-13511dc6fd57.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/331116/79061288-dce45680-7cb8-11ea-8cf2-2dd0dc90ceaf.png)

**Comment by aleksandar-olic** [comment]
Sorry about that, we can't test it because we only have access to the latest version, plus there are hundreds of old versions and we can't keep up with them.

You could try adding your custom domain in the extension's Settings and see if that solves the issue (you'll need to open "URL Permissions" in the extension, scroll down to the bottom, select "Custom Atlassian" and type your custom domain, without the "https://" part, and Save).

If that doesn't help, you can fork this repo and see if you can make it compatible with your version of Jira. Another solution is to select the issue name and start the timer from right-click menu.
