### ISSUE TITLE
V1.6.2 removed Start Timer link from Jira

### ISSUE THREAD

**Issue by arueber** [clockify/browser-extension#8]
Before my browser updated with V1.6.2, I could see the Start Timer link in Jira but since the update have not been able. I have not changed my settings in the Chrome extension.

![image](https://user-images.githubusercontent.com/11856187/59795054-faff4700-929f-11e9-80ba-5e0b5cb8b30e.png)

**Comment by cedomirm1990** [comment]
Thanks for reporting this, arueber!

You're right, it seems like Jira made some changes which is why the timer is now missing and we noted it down so we can take a look at it.

Since we're currently working on some more urgent matter it might take a while to fix this. If you don’t want to wait for us to do it, feel free to fix it yourself by contributing to our code base.

**Comment by edgargp** [comment]
any news regarding this issue ?

**Comment by cedomirm1990** [comment]
Hello edgargp, 

It will be done in next few days, we will let you know about updates.

Cheers!

**Comment by edgargp** [comment]
Hi cedomirm1990,
Ok thank  you

**Comment by malizmaj** [comment]
Fix is now live

**Comment by grantlucas** [comment]
Does anything need to happen to get this to work? Everyone on my team is still missing the start timer button in Jira. Old and new UI.
